# The IP to listen to. Use 0.0.0.0 if you wish to listen to all interfaces on your server. (All IP addresses)
# This defaults to the IP you have configured your server to listen on, or 0.0.0.0 if you have not configured this.
host: 0.0.0.0

# Port to listen for new votes on
port: 8192

# Whether or not to print debug messages. In a production system, this should be set to false.
# This is useful when initially setting up NuVotifier to ensure votes are being delivered.
debug: true

# All tokens, labeled by the serviceName of each server list.
tokens:
  # Default token for all server lists, if another isn't supplied.
  default: standaloneDefaultToken

# Setting this option to true will disable handling of Protocol v1 packets. While the old protocol is not secure, this
# option is currently not recommended as most voting sites only support the old protocol at present.
disable-v1-protocol: false

# Redis forwarding settings.
# If disabled, we will fall back to the 'proxy' forwarding mode.
redis:
  enabled: false
  address: 127.0.0.1
  port: 6379
  password: ""
  channel: nuvotifier:votes
  pool-settings:
    timeout: 5000
    max-total: 128
    max-idle: 128
    min-idle: 16
    min-evictable-idle-time: 60000
    time-between-eviction-runs: 30000
    num-tests-per-eviction-run: 3
    block-when-exhausted: true

# Configuration section for all vote forwarding to NuVotifier
forwarding:
  # Specify servers to proxy votes for.
  lobby:
    address: 127.0.0.1
    port: 8193
    token: lobbyToken
  skyblock:
    address: 127.0.0.1
    port: 8194
    token: skyblockToken